NumPy Dizisi (Array) Oluşturma ve Veri Tipi Değiştirme

In [1]:
import numpy as np

In [2]:
list1 = np.array([1,2,3,4,5])
print("list1:", list1)
print(type(list1))

list1: [1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
print("list1 veri tipi: ", list1.dtype)

list1 veri tipi:  int64


In [4]:
list1_float=list1.astype(np.float64)
list1_float.dtype


dtype('float64')

 Çok Boyutlu Dizi (Matrix) Oluşturma ve Erişim

In [5]:
matris = np.array([[1,2,3], [4,5,6]])
print("matris:\n",matris)

matris:
 [[1 2 3]
 [4 5 6]]


In [6]:
print("matrisin boyutları:", np.shape(matris))

matrisin boyutları: (2, 3)


In [7]:
matris[0,2]

np.int64(3)

Dizi Üzerinde Matematiksel İşlemler

In [8]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print("toplama:", a + b)
print("çıkarma:", a - b)
print("çarpma:", a * b)
print("bölme:", a / b)
print("elemanların karesi:", a ** 2)
print("ortalama:", np.mean(a))

toplama: [5 7 9]
çıkarma: [-3 -3 -3]
çarpma: [ 4 10 18]
bölme: [0.25 0.4  0.5 ]
elemanların karesi: [1 4 9]
ortalama: 2.0


Dizi Boyutunu Değiştirme (Reshape)

In [9]:
dizi1 = np.random.randint(0,30,(6,5))
print("dizi1:\n", dizi1)

dizi1:
 [[26 14  2 28 22]
 [ 2 15  2 19  7]
 [18 19 24 25 19]
 [ 9  0 29 15  1]
 [ 6  0 14 13 14]
 [ 1 18  7 26  4]]


In [10]:
dizi1.reshape(30)

array([26, 14,  2, 28, 22,  2, 15,  2, 19,  7, 18, 19, 24, 25, 19,  9,  0,
       29, 15,  1,  6,  0, 14, 13, 14,  1, 18,  7, 26,  4], dtype=int32)

In [11]:
dizi1.reshape(5,6)

array([[26, 14,  2, 28, 22,  2],
       [15,  2, 19,  7, 18, 19],
       [24, 25, 19,  9,  0, 29],
       [15,  1,  6,  0, 14, 13],
       [14,  1, 18,  7, 26,  4]], dtype=int32)

Dizi İçinden Belirli Koşula Göre Eleman Seçme (Boolean Indexing)

In [12]:
dizi2 = np.random.randint(0,100,(10,4))
dizi2

array([[43, 53, 97,  9],
       [43, 28, 36, 16],
       [23, 44, 88, 86],
       [48, 97, 10, 70],
       [78, 84, 56, 45],
       [35, 39, 56, 57],
       [71, 66, 87, 61],
       [73, 90, 26, 88],
       [19,  4, 36, 95],
       [24,  1, 58, 36]], dtype=int32)

In [13]:
dizi2 > 50

array([[False,  True,  True, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [False,  True, False,  True],
       [ True,  True,  True, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [False, False, False,  True],
       [False, False,  True, False]])

In [14]:
dizi2[dizi2>50]

array([53, 97, 88, 86, 97, 70, 78, 84, 56, 56, 57, 71, 66, 87, 61, 73, 90,
       88, 95, 58], dtype=int32)

In [15]:
print((dizi2 > 50) & (dizi2 < 80))

[[False  True False False]
 [False False False False]
 [False False False False]
 [False False False  True]
 [ True False  True False]
 [False False  True  True]
 [ True  True False  True]
 [ True False False False]
 [False False False False]
 [False False  True False]]


In [16]:
dizi2[dizi2 >50][dizi2[dizi2 > 50] < 80]

array([53, 70, 78, 56, 56, 57, 71, 66, 61, 73, 58], dtype=int32)