In [2]:
import numpy as np

NUMPY İLE NOKTA DOĞRU DÜZLEM VE UZAY

In [3]:
skaler = np.array(90)
vektorel = np.array([1, 2, 3, 4, 5])
matris = np.array([[1, 2], [3, 4],[5,6]])
print("Skaler:", skaler)
print("Vektörel:", vektorel)
print("Matris: \n", matris)


Skaler: 90
Vektörel: [1 2 3 4 5]
Matris: 
 [[1 2]
 [3 4]
 [5 6]]


In [4]:
tensor = np.array([[[1, 2],[3, 4]],[[5, 6],[7,8]]])
print("Tensor: \n" , tensor)

Tensor: 
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


SIZE SHAPE DTYPE NDIM

In [5]:
liste = np.array(range(1, 11))
matris = np.array([[1,2], [3,4], [5,6], [7,8], [9,10]])
print("Liste: \n", liste)
print("size: ", liste.size)
print("shape: ", liste.shape)
print("uzayda kapladığı boyut:" , liste.ndim)
print("data type : ", liste.dtype)
print("Matris: \n", matris)
print("size: ", matris.size)
print("shape: ", matris.shape)
print("uzayda kapladığı boyut:" , matris.ndim)
print("data type : ", matris.dtype)

Liste: 
 [ 1  2  3  4  5  6  7  8  9 10]
size:  10
shape:  (10,)
uzayda kapladığı boyut: 1
data type :  int64
Matris: 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
size:  10
shape:  (5, 2)
uzayda kapladığı boyut: 2
data type :  int64


NUMPY ARRAY

In [6]:
benimListem = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
np.array(benimListem)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
matrixListesi = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
np.array(matrixListesi)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ARANGE

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2,15,3)

array([ 2,  5,  8, 11, 14])

ZEROS / ONES / FULL

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
np.ones((9,9))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.full((3,3),19)

array([[19, 19, 19],
       [19, 19, 19],
       [19, 19, 19]])

LİNSPACE

In [15]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [16]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

EYE

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
np.eye(10 , k=5)

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

RANDOM

In [21]:
np.random.randn(9)

array([ 0.78082645,  0.66753594, -0.11543882,  0.23200377,  0.66556474,
        0.16600188, -2.23310183, -0.00665771, -0.09569012])

In [22]:
np.random.randn(2,2)

array([[-0.06083806,  0.45084778],
       [ 0.22050167, -0.46277944]])

In [23]:
np.random.randint(1, 10)

7

In [24]:
np.random.randint(1,10,6)

array([7, 8, 9, 9, 2, 2], dtype=int32)

In [25]:
np.random.rand(5)

array([0.41828161, 0.02489749, 0.86928233, 0.2131325 , 0.56058043])

In [26]:
benimNumpyDizim = np.arange(30)
benimNumpyDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
benimNumpyDizim2 = benimNumpyDizim.reshape(5,6)
np.diag(benimNumpyDizim2)


array([ 0,  7, 14, 21, 28])

In [28]:
benimNumpyDizim2 = np.linspace(25,100,3)
benimNumpyDizim2

array([ 25. ,  62.5, 100. ])

In [29]:
benimRandomDizim = np.random.randint(0,30,100)
benimRandomDizim

array([10, 14, 25, 28, 24,  3,  3, 25, 16,  6, 22,  8, 22, 26,  1, 12,  9,
        3, 10, 19, 27, 22,  2,  1, 23,  7, 28,  2, 24, 23, 10, 10, 17,  5,
       19, 13,  3, 20,  1, 22, 21, 20, 24,  3, 13, 11, 22, 26, 11, 14, 20,
       10, 21, 27,  9, 12, 19, 10, 28,  8,  0, 19, 27, 22, 27,  2, 19, 13,
       15, 12,  8, 25,  2, 20, 27, 27,  1,  1, 27, 20,  8,  1, 15,  1, 10,
        0,  4, 26, 18,  1, 13, 29, 20,  0,  2,  1,  7, 16,  0,  4],
      dtype=int32)

NUMPY DİZİ METODLARI

In [30]:
benimNumpyDizim.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
np.diag(benimNumpyDizim.reshape(6,5))

array([ 0,  6, 12, 18, 24])

In [32]:
benimRandomDizim.max()

np.int32(29)

In [33]:
benimRandomDizim.min()

np.int32(0)

In [34]:
benimRandomDizim.argmax()

np.int64(91)

In [35]:
benimRandomDizim.argmin()

np.int64(60)

In [36]:
benimNumpyDizim.shape

(30,)

In [37]:
reshapeDizim = benimNumpyDizim.reshape(5,6)
reshapeDizim.shape

(5, 6)

In [38]:
benimDizim = np.arange(0,15)
benimDizim

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
benimDizim[5]

np.int64(5)

In [40]:
benimDizim[3:15]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
benimDizim[2:8] = 100
benimDizim

array([  0,   1, 100, 100, 100, 100, 100, 100,   8,   9,  10,  11,  12,
        13,  14])

In [42]:
baskaDizi = np.arange(0,24)
baskaDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [43]:
slicingDizi = baskaDizi[4:9]
print("slicing dizi = " ,slicingDizi)
print("başka dizi = " ,baskaDizi)

slicing dizi =  [4 5 6 7 8]
başka dizi =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [44]:
slicingDizi[:]

array([4, 5, 6, 7, 8])

In [45]:
slicingDizi[:] = 1000
slicingDizi

array([1000, 1000, 1000, 1000, 1000])

🧠 NumPy Dizilerinde Slicing (Dilimleme) ve Orijinal Diziyi Etkilemesi
NumPy'de dizilerle çalışırken, bir dizinin bir alt bölümünü (subarray) almak için dilimleme (slicing) kullanılır. Ancak, Python listelerinden farklı olarak, NumPy'de bir dizi üzerinde yapılan dilimleme işlemi, verinin bir kopyasını oluşturmaz, orijinal dizinin bir görünümünü (view) oluşturur.

🔍 Önemli Terimler
Slicing (Dilimleme): Dizinin belli bir bölümünü : (iki nokta) sembolüyle seçme işlemidir.

View (Görünüm): Orijinal veriye bağlı olan alt dizidir. Üzerinde yapılan değişiklikler ana diziyi etkiler.
Yani, dilimde yapılan değişiklikler orijinal diziyi etkiler.

Copy (Kopya): Orijinal veriden bağımsız yeni bir dizidir. Değişiklikler ana diziyi etkilemez.

In [46]:
baskaDizi

array([   0,    1,    2,    3, 1000, 1000, 1000, 1000, 1000,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

🧷 NumPy'de Slicing Sonucunda Orijinal Dizinin Değişmesini Önlemek
NumPy'de bir diziden parça almak için yapılan slicing (dilimleme) işlemi, verinin bir kopyasını değil, bir görünümünü (view) oluşturur. Bu yüzden, bu görünüm üzerinde yapılan değişiklikler orijinal diziyi (original array) de etkiler.

Bu durumu engellemek için, dilimleme işleminden sonra copy() metodunu kullanarak bağımsız bir kopya alınmalıdır.

In [47]:
ornekDizi = np.arange(0,20)
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [48]:
ornekDiziKopya = ornekDizi.copy()
ornekDiziKopya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
ornekDiziKopya

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
ornekDiziKopyaSlicing = ornekDiziKopya[5:10]
ornekDiziKopyaSlicing[:] = 1000
print("örnek dizi kopya dilim = ", ornekDiziKopyaSlicing)
print("örnek dizi kopya",ornekDiziKopya)
print("ornek dizi", ornekDizi)

örnek dizi kopya dilim =  [1000 1000 1000 1000 1000]
örnek dizi kopya [   0    1    2    3    4 1000 1000 1000 1000 1000   10   11   12   13
   14   15   16   17   18   19]
ornek dizi [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
ornekDiziKopyaSlicing[:] = 900
ornekDiziKopyaSlicing

array([900, 900, 900, 900, 900])

In [52]:
ornekDiziKopya

array([  0,   1,   2,   3,   4, 900, 900, 900, 900, 900,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [53]:
ornekDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

MATRİX İŞLEMLERİ 

In [54]:
ornekMatrixDizi = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
ornekMatrixDizi

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
type(ornekMatrixDizi)

numpy.ndarray

In [56]:
ornekMatrixDizi[0]

array([1, 2, 3])

In [57]:
ornekMatrixDizi[1,2]

np.int64(6)

In [58]:
ornekMatrixDizi[1:,1]

array([5, 8])

In [59]:
ornekMatrixDizi[0:,2]

array([3, 6, 9])

In [60]:
yeniListe = ([list(range(0,5)),list(range(5,10)),list(range(10,15)),list(range(15,20))])
yeniListe

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]]

In [61]:
yeniMatrix = np.array(yeniListe)
yeniMatrix

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [62]:
yeniMatrix[2]

array([10, 11, 12, 13, 14])

In [63]:
yeniMatrix[[0, 2, 3]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

OPERASYONLAR

In [64]:
yeniBirDizi = np.random.randint(1,100,25)
yeniBirDizi

array([76, 86, 65, 23,  3, 45, 83, 88, 56, 99, 26, 67, 81, 98, 25, 97, 57,
        7,  6, 15, 90, 12, 38,  4, 96], dtype=int32)

In [65]:
sonucDizisi = yeniBirDizi > 24
sonucDizisi

array([ True,  True,  True, False, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True, False,  True])

In [66]:
yeniBirDizi

array([76, 86, 65, 23,  3, 45, 83, 88, 56, 99, 26, 67, 81, 98, 25, 97, 57,
        7,  6, 15, 90, 12, 38,  4, 96], dtype=int32)

In [67]:
yeniBirDizi[sonucDizisi]

array([76, 86, 65, 45, 83, 88, 56, 99, 26, 67, 81, 98, 25, 97, 57, 90, 38,
       96], dtype=int32)

In [68]:
sonDizi = np.arange(0,24)
sonDizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [69]:
sonDiziToplam = sonDizi + sonDizi
sonDiziToplam

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46])

In [70]:
sonDiziCarpim = sonDizi * sonDizi
sonDiziCarpim

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529])

In [71]:
sonDiziFark = sonDizi - sonDizi
sonDiziFark

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [72]:
sonDiziBolum = sonDizi / sonDizi
sonDiziBolum

C:\Users\ebeng\AppData\Local\Temp\ipykernel_11232\1747164899.py:1: RuntimeWarning: invalid value encountered in divide
  sonDiziBolum = sonDizi / sonDizi


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [73]:
np.sqrt(sonDizi)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152])

In [74]:
print("Maximum Değer:" ,np.max(sonDizi))
print("Minimum Değer:" ,np.min(sonDizi))

Maximum Değer: 23
Minimum Değer: 0


In [75]:
dizi = np.arange(0,10)
print(dizi.shape)

(10,)


In [76]:
np.empty((3,4))

array([[7.19696324e-312, 2.47032823e-322, 0.00000000e+000,
        0.00000000e+000],
       [2.22809558e-312, 8.60952352e-072, 5.33840028e-091,
        1.83119717e-076],
       [2.32690721e-057, 3.11035843e+179, 3.99910963e+252,
        5.82471487e+257]])

In [77]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.concatenate((a, b)))  # [1 2 3 4]


[1 2 3 4]


 Senaryo:
Bir sınıftaki 5 öğrencinin 3 dersten aldığı notlar aşağıdaki gibidir. Bu notları NumPy kullanarak analiz edeceğiz:

In [78]:
#NOTLAR
notlar = np.array([
    [85,75,60],
    [90,80,70],      
    [95,88,92], 
    [70,65,80], 
    [88,90,85]
])
notlar

array([[85, 75, 60],
       [90, 80, 70],
       [95, 88, 92],
       [70, 65, 80],
       [88, 90, 85]])

In [79]:
#HER ÖĞRENCİNİN ORTALAMASI
ogrenci_ortalama = np.mean(notlar,axis=1) #yatay
print("öğrenci ortalama : " ,ogrenci_ortalama)
ders_ortalama = np.mean(notlar,axis=0) #dikey
print("ders ortalama : " ,ders_ortalama)

öğrenci ortalama :  [73.33333333 80.         91.66666667 71.66666667 87.66666667]
ders ortalama :  [85.6 79.6 77.4]


In [80]:
notlar < 70
[notlar[notlar<70]]

[array([60, 65])]

In [81]:
mask = notlar < 70
print("70 Altı Notlar (True = düşük):")
print(mask)


70 Altı Notlar (True = düşük):
[[False False  True]
 [False False False]
 [False False False]
 [False  True False]
 [False False False]]


In [82]:
gecen_sayilar = np.sum(notlar >= 70, axis=0)
print("Her dersten geçen öğrenci sayısı:", gecen_sayilar)


Her dersten geçen öğrenci sayısı: [5 4 4]


In [83]:
en_yuksek = np.max(notlar)
en_dusuk = np.min(notlar)

print("En yüksek not:", en_yuksek)
print("En düşük not:", en_dusuk)


En yüksek not: 95
En düşük not: 60


In [84]:
yeniNotlar = notlar + 5
print("Yeni Notlar (5 puan artırılmış):")
print(yeniNotlar)

Yeni Notlar (5 puan artırılmış):
[[ 90  80  65]
 [ 95  85  75]
 [100  93  97]
 [ 75  70  85]
 [ 93  95  90]]


In [85]:
matris = np.random.randint(1, 100, (5, 5))
matris

array([[99, 35, 75, 12, 79],
       [85, 19, 65, 50, 49],
       [44, 60,  3, 94, 76],
       [84, 65, 28, 15, 17],
       [48, 17, 72, 59, 51]], dtype=int32)

In [86]:
matris_Transpose = matris.T
print("Matrisin Transpozu:")
print(matris_Transpose)

Matrisin Transpozu:
[[99 85 44 84 48]
 [35 19 60 65 17]
 [75 65  3 28 72]
 [12 50 94 15 59]
 [79 49 76 17 51]]
